# Generated by Django 5.2.7 on 2025-11-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_comment_time_alter_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='extra_links',
            field=models.TextField(blank=True, help_text='Enter multiple links separated by commas', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(blank=True, default='05 November 2025', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(blank=True, default='05 November 2025', max_length=100),
        ),
    ]
