# Generated by Django 5.2.7 on 2025-11-05 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_post_extra_links_post_youtube_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='extra_links',
        ),
    ]
