# Generated by Django 5.2.7 on 2025-11-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_post_extra_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='youtube_link',
        ),
    ]
