# Generated by Django 5.1.3 on 2025-11-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0019_remove_post_youtube_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="time",
            field=models.CharField(
                blank=True, default="06 November 2025", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.CharField(
                blank=True, default="06 November 2025", max_length=100
            ),
        ),
    ]
