# Generated by Django 5.2.7 on 2025-11-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_post_youtube_link_alter_comment_time_alter_post_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='youtube_link',
        ),
    ]
