# Generated by Django 5.1.3 on 2025-11-06 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0020_alter_comment_time_alter_post_time"),
        ("myapp", "0021_remove_post_youtube_link"),
    ]

    operations = []
